version: '3.8'
 
services:
  postgres:
    image: postgres:latest
    container_name: meu_postgres
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: banco
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
 
volumes:
  db_data: